---
- hosts: all
  vars:
    key: /etc/apt/keyrings/redis-archive-keyring.gpg
    version: 6:7.4.8-1rl1~noble1

  handlers:
    - name: restart redis
      service: name=redis-server state=restarted
  
  tasks:
  - name: Add Redis Key
    apt_key:
      url: https://packages.redis.io/gpg
      keyring: "{{ key }}"
      state: present

  - name: Add Redis Repo
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: redis
    loop:
      - deb [signed-by={{ key }}] https://packages.redis.io/deb {{ ansible_facts["distribution_release"] }} main
  
  - name: Install Redis
    apt:
      name:
        - "redis={{ version }}"
        - "redis-server={{ version }}"
        - "redis-tools={{ version}}"
        # - "redis-sentinel={{ version }}"

  - name: allow remote connect
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^bind'
      line: 'bind 0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^protected-mode'
      line: 'protected-mode no'
    notify: restart redis
